name: registry
title: Registry
version: '3.1.0'
summary: Local OCI Image Registry
description: |
  Simple snap package to set up a local OCI Image Registry using the CNCF
  Distribution project from https://github.com/distribution/distribution/.
source-code: https://github.com/canonical/registry-snap
# TODO: define license

grade: stable
confinement: strict

base: core24

platforms:
  amd64:
  arm64:

parts:
  misc:
    plugin: dump
    source: ./scripts
  registry:
    plugin: go
    source-type: git
    source: https://github.com/distribution/distribution
    source-tag: v3.1.0
    build-environment:
      - CGO_ENABLED: "0"
      - GOTOOLCHAIN: local
    build-snaps:
      - go/1.25/stable
    prime:
      - bin/registry

apps:
  registry:
    command: run-registry
    daemon: simple
    plugs: [network-bind]
