name: registry
title: OCI Image Registry
# TODO: update to match registry version
version: '0.2'
summary: OCI Image Registry (from CNCF Distribution) packaged as a snap
description: |
  [CNCF Distribution Registry](https://github.com/distribution/distribution/) packaged as a snap.
source-code: https://github.com/canonical/registry-snap
# TODO: define license

grade: stable
confinement: strict

base: core24

platforms:
  amd64:
  #arm64:

parts:
  misc:
    plugin: dump
    source: ./scripts
  registry:
    plugin: go
    source-type: git
    # TODO: pin to a version
    source: https://github.com/distribution/distribution/
    build-environment:
    - CGO_ENABLED: "0"
    build-snaps:
      - go
    prime:
    - bin/registry

apps:
  registry:
    command: run-registry
    daemon: simple
    plugs: [network-bind]
