name: registry
title: OCI Image Registry
version: '3.1.0'
summary: OCI Image Registry (from CNCF Distribution) packaged as a snap
description: |
  [CNCF Distribution Registry](https://github.com/distribution/distribution/) packaged as a snap.
source-code: https://github.com/canonical/registry-snap
# TODO: define license

grade: stable
confinement: strict

base: core24

platforms:
  amd64:
  #arm64:

parts:
  misc:
    plugin: dump
    source: ./scripts
  registry:
    plugin: go
    source-type: git
    source: https://github.com/distribution/distribution/tree/v3.1.0
    build-environment:
    - CGO_ENABLED: "0"
    build-snaps:
      - go
    prime:
    - bin/registry

apps:
  registry:
    command: run-registry
    daemon: simple
    plugs: [network-bind]
