# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: E2E tests

on:
  workflow_call:
    inputs:
      artifact-prefix:
        description: Snap artifact prefix from build job
        required: true
        type: string

jobs:
  e2e:
    name: E2E tests | ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    permissions:
      actions: read  # Needed to download workflow artifacts
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    steps:
      - name: Download snap artifact
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ inputs.artifact-prefix }}*--platform-${{ matrix.arch }}
          merge-multiple: true

      - name: Install registry snap
        run: sudo snap install --dangerous ./*.snap

      - name: Set up docker
        run: |
          sudo snap install docker
          sudo addgroup --system docker
          sudo adduser $USER docker
          sudo snap restart docker
          timeout 60 sh -c 'until sg docker -c "docker info" > /dev/null 2>&1; do sleep 1; done'

      - name: Clone distribution repository
        run: git clone --depth 1 --branch v3.1.0 https://github.com/distribution/distribution

      - name: Run e2e tests
        run: |
          cd distribution
          sg docker -c "bash ./tests/push.sh 127.0.0.0"
