# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to Snap Store edge branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@df6c1fd905a8fdc5db0771f35edf92d1a108020a  # v49.0.0
    permissions:
      actions: read  # Needed for GitHub API call to get workflow version
      contents: read

  e2e:
    name: E2E tests
    needs:
      - build
    uses: ./.github/workflows/e2e.yaml
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    permissions:
      actions: read
      contents: read

  release:
    name: Release snap to Snap Store branch
    # Be sure this is restricted to internal users
    if: github.event.pull_request.head.repo.full_name == github.repository
    needs:
      - build
      - e2e
    uses: canonical/data-platform-workflows/.github/workflows/release_snap_pr.yaml@df6c1fd905a8fdc5db0771f35edf92d1a108020a  # v49.0.0
    with:
      track: 'latest'
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets:
      snap-store-token: ${{ secrets.SNAP_STORE_TOKEN_EDGE_PR }}
    permissions:
      actions: read  # Needed for GitHub API call to get workflow version
      contents: read
